name: cruddappergraphql
services:

    sqlexpress2022:
        container_name: sqlexpress2022
        image: mcr.microsoft.com/mssql/server:2022-CU15-GDR1-ubuntu-22.04
        ports:
            - 1433:1433
        volumes:
             - sqldata2022:/var/opt/mssql
             - ./CrudDapperGraphQL/Data/Migrations:/usr/src/app
        hostname:
            sqlexpress2022host
        environment:
            ACCEPT_EULA: Y
            MSSQL_SA_PASSWORD: ${SERVER_PWD}
            MSSQL_COLLATION: SQL_Latin1_General_CP1_CI_AS
            MSSQL_PID: Express
        command:
            - /bin/bash
            - -c
            - |
                /opt/mssql/bin/sqlservr & sleep 10;
                /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P "${SERVER_PWD}" -d master -q "CREATE LOGIN developer WITH PASSWORD = '${DEVELOPER_PWD}'" -C;
                /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P "${SERVER_PWD}" -d master -i /usr/src/app/init.sql -C;
                /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P "${SERVER_PWD}" -d master -i /usr/src/app/migration.sql -C;
                wait

    webapp:
        container_name: web-app
        image: leviserg/cruddappergraphql-web-app:v1.0
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - EXPOSE_PORT=${APP_HTTP_PORT}
        ports:
            - ${APP_HTTP_PORT}:${APP_HTTP_PORT}
        environment:
            ASPNETCORE_HTTP_PORTS: ${APP_HTTP_PORT}
            ASPNETCORE_ENVIRONMENT: Development
            BookLibraryServiceAccount: ${APP_ACCOUNT}
            BookLibraryDbConnection: ${APP_DBCONN}
        
volumes:
    sqldata2022: